name: release

on: workflow_dispatch
#on:
#  push:
#    tags:
#      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore src/BlazorApp.csproj
    - name: Build code
      run: dotnet build src/BlazorApp.csproj --configuration Release --no-restore
    - name: Publish application
      run: dotnet publish src/BlazorApp.csproj -c Release -o BlazorDemo
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: BlazorDemo
       path: BlazorDemo 
  release:
    name: build_release
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
   


    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: BlazorApp.linux-amd64.tar.gz
        asset_name: BlazorApp.linux-amd64.tar.gz
        asset_content_type: application/gzip
    - name: upload darwin artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: BlazorApp.darwin-amd64.tar.gz
        asset_name: BlazorApp.darwin-amd64.tar.gz
        asset_content_type: application/gzip
    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: BlazorAppr.windows-amd64.zip
        asset_name: BlazorApp.windows-amd64.zip
        asset_content_type: application/zip
